INSERT INTO PUBLIC.LANGUAGE (CODE, INFO) VALUES ('en', 'English');
INSERT INTO PUBLIC.LANGUAGE (CODE, INFO) VALUES ('ru', 'Русский');
INSERT INTO PUBLIC.LANGUAGE (CODE, INFO) VALUES ('by', 'Беларускі');