INSERT INTO PUBLIC.PART_OF_SPEECH (CODE, INFO) VALUES ('noun', 'Naming word');
INSERT INTO PUBLIC.PART_OF_SPEECH (CODE, INFO) VALUES ('verb', 'Action Word');
INSERT INTO PUBLIC.PART_OF_SPEECH (CODE, INFO) VALUES ('interjection', 'Expressive word');